set(current_dir ${CMAKE_CURRENT_LIST_DIR})

function(gen_version_code VAR)

    set(ARG_VERSION_CODE "0")

    if (DEFINED PROJECT_VERSION_MAJOR AND NOT PROJECT_VERSION_MAJOR STREQUAL "")
        if (PROJECT_VERSION_MAJOR LESS "2100" AND PROJECT_VERSION_MAJOR GREATER "-1")
            math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + ${PROJECT_VERSION_MAJOR} * 1000000")
        else ()
            message(FATAL_ERROR "QtAppBase: PROJECT_VERSION_MAJOR exceeding the allowed range of [0, 2099]")
        endif ()
    endif ()
    if (DEFINED PROJECT_VERSION_MINOR AND NOT PROJECT_VERSION_MINOR STREQUAL "")
        if (PROJECT_VERSION_MINOR LESS "100" AND PROJECT_VERSION_MINOR GREATER "-1")
            math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + ${PROJECT_VERSION_MINOR} * 10000")
        else ()
            message(FATAL_ERROR "QtAppBase: PROJECT_VERSION_MINOR exceeding the allowed range of [0, 99]")
        endif ()
    endif ()
    if (DEFINED PROJECT_VERSION_PATCH AND NOT PROJECT_VERSION_PATCH STREQUAL "")
        if (PROJECT_VERSION_PATCH LESS "100" AND PROJECT_VERSION_PATCH GREATER "-1")
            math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + ${PROJECT_VERSION_PATCH} * 100")
        else ()
            message(FATAL_ERROR "QtAppBase: PROJECT_VERSION_PATCH exceeding the allowed range of [0, 99]")
        endif ()
    endif ()
    if (DEFINED PROJECT_VERSION_TWEAK AND NOT PROJECT_VERSION_TWEAK STREQUAL "")
        if (PROJECT_VERSION_TWEAK LESS "10" AND PROJECT_VERSION_TWEAK GREATER "-1")
            math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + ${PROJECT_VERSION_TWEAK} * 10")
        else ()
            message(FATAL_ERROR "QtAppBase: PROJECT_VERSION_TWEAK exceeding the allowed range of [0, 9]")
        endif ()
    endif ()
    if (CMAKE_ANDROID_ARCH_ABI STREQUAL "arm64-v8a")
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 1")
    elseif (CMAKE_ANDROID_ARCH_ABI STREQUAL "armeabi-v7a" AND NOT CMAKE_ANDROID_ARM_NEON)
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 2")
    elseif (CMAKE_ANDROID_ARCH_ABI STREQUAL "armeabi-v7a" AND CMAKE_ANDROID_ARM_NEON)
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 3")
    elseif (CMAKE_ANDROID_ARCH_ABI STREQUAL "armeabi-v6")
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 4")
    elseif (CMAKE_ANDROID_ARCH_ABI STREQUAL "armeabi")
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 5")
    elseif (CMAKE_ANDROID_ARCH_ABI STREQUAL "mips")
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 6")
    elseif (CMAKE_ANDROID_ARCH_ABI STREQUAL "mips64")
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 7")
    elseif (CMAKE_ANDROID_ARCH_ABI STREQUAL "x86")
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 8")
    elseif (CMAKE_ANDROID_ARCH_ABI STREQUAL "x86_64")
        math(EXPR ARG_VERSION_CODE "${ARG_VERSION_CODE} + 9")
    else ()
        message(WARNING "QtAppBase: Couldn't read valid CMAKE_ANDROID_ARCH_ABI. The VERSION_CODE won't be distinguishable between different abi's")
    endif ()

    set(${VAR} ${ARG_VERSION_CODE} PARENT_SCOPE)
endfunction()

function(install_android TARGET)

    get_target_property(APP_ANDROID_PACKAGE_SOURCE_DIR ${TARGET} QT_ANDROID_PACKAGE_SOURCE_DIR)
    if (APP_ANDROID_PACKAGE_SOURCE_DIR)
        message(STATUS "QtAppBase: QT_ANDROID_PACKAGE_SOURCE_DIR target property already set - using provided AndroidManifest.xml")
        if (EXISTS "${APP_ANDROID_PACKAGE_SOURCE_DIR}/AndroidManifest.xml.in")
            configure_file("${APP_ANDROID_PACKAGE_SOURCE_DIR}/AndroidManifest.xml.in" "${APP_ANDROID_PACKAGE_SOURCE_DIR}/AndroidManifest.xml" @ONLY)
        endif ()
    else ()
        configure_file("${current_dir}/AndroidManifest.xml.in" "${CMAKE_CURRENT_BINARY_DIR}/android_package_src/AndroidManifest.xml" @ONLY)
        set_target_properties(${TARGET} PROPERTIES QT_ANDROID_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_BINARY_DIR}/android_package_src")
    endif ()
    gen_version_code(VERSION_CODE)
    set_target_properties(${TARGET} PROPERTIES QT_ANDROID_VERSION_CODE "${VERSION_CODE}")
    set_target_properties(${TARGET} PROPERTIES QT_ANDROID_VERSION_NAME "${PROJECT_VERSION}")
    message(STATUS "QtAppBase: Using Android Version Code '${VERSION_CODE}' and Version Name '${PROJECT_VERSION}'")
    install(FILES "${CMAKE_CURRENT_BINARY_DIR}/android-build/$<TARGET_NAME:${TARGET}>.apk" DESTINATION .)
    install(CODE "execute_process(COMMAND adb install \"${CMAKE_CURRENT_BINARY_DIR}/android-build/$<TARGET_NAME:${TARGET}>.apk\")")
endfunction()
