# copy_replace_in_file(<filename> [REGEX] DESTINATION <dst> MATCH <match_string> REPLACE <replace replace_string>)
function(copy_replace_in_file)
    set(options REGEX)
    set(oneValueArgs DESTINATION MATCH REPLACE)
    set(multiValueArgs)
    cmake_parse_arguments(CP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    file(READ "${ARGV0}" FILE_CONTENT)
    if (CP_MATCH AND CP_REPLACE)
        if (CP_REGEX)
            string(REGEX REPLACE ${CP_MATCH} ${CP_REPLACE} REPLACED_CONTENT ${FILE_CONTENT})
        else ()
            string(REPLACE ${CP_MATCH} ${CP_REPLACE} REPLACED_CONTENT ${FILE_CONTENT})
        endif ()
    endif ()
    file(WRITE "${CP_DESTINATION}" ${REPLACED_CONTENT})
endfunction()

# replace_in_file(<filename> [REGEX] MATCH <match_string> REPLACE <replace replace_string>)
function(replace_in_file)
    set(options REGEX)
    set(oneValueArgs MATCH REPLACE)
    set(multiValueArgs)
    cmake_parse_arguments(CP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
    file(READ "${ARGV0}" FILE_CONTENT)
    if (CP_MATCH AND CP_REPLACE)
        if (CP_REGEX)
            string(REGEX REPLACE ${CP_MATCH} ${CP_REPLACE} REPLACED_CONTENT ${FILE_CONTENT})
        else ()
            string(REPLACE ${CP_MATCH} ${CP_REPLACE} REPLACED_CONTENT ${FILE_CONTENT})
        endif ()
    endif ()
    file(WRITE "${ARGV0}" ${REPLACED_CONTENT})
endfunction()

# create_mime_mappings(<target> <mapping file basename> <out dir>)
function(create_mime_mappings TARGET MAPPING_NAME OUT_DIR)

    get_target_property(APPBASE_ASSOCIATED_EXTENSIONS ${TARGET} APPBASE_ASSOCIATED_EXTENSIONS)
    if (APPBASE_ASSOCIATED_EXTENSIONS)
        foreach (APPBASE_ASSOCIATED_EXTENSION ${APPBASE_ASSOCIATED_EXTENSIONS})
            string(REPLACE "," ";" mime_type_ "${APPBASE_ASSOCIATED_EXTENSION}")
            list(GET mime_type_ 0 glob_pattern)
            list(GET mime_type_ 1 mime_type)
            list(GET mime_type_ 2 comment)
            configure_file("${current_dir}/mimeMap.xml.in" "${OUT_DIR}/${MAPPING_NAME}.xml" @ONLY)
        endforeach ()
    endif ()
endfunction()

# Read a icon from the given target with the given type. If not found <out image path> equals NOTFOUND
# get_target_icon(<target> [SCALABLE | ICO | 1024x1024 | ...] <out image path>)
function(get_target_icon TARGET ICON_NAME ICON_PATH)

    set(${ICON_PATH} "NOTFOUND" PARENT_SCOPE)
    get_target_property(APPBASE_ICONS ${TARGET} APPBASE_ICON)
    if (APPBASE_ICONS)
        string(REPLACE "^^" ";" APPBASE_ICONS_SPLIT "${APPBASE_ICONS}")
        foreach (APPBASE_ICON ${APPBASE_ICONS_SPLIT})
            string(REPLACE "^_" ";" icon_ "${APPBASE_ICON}")
            list(GET icon_ 0 icon_res)
            list(GET icon_ 1 icon_location)
            if (icon_res STREQUAL ICON_NAME)
                if (icon_location)
                    set(${ICON_PATH} "${icon_location}" PARENT_SCOPE)
                    break()
                endif ()
            endif ()
        endforeach ()
    endif ()
endfunction()

function(create_appimage_icons_dir TARGET ICON_NAME OUT_DIR PRIMARY_ICON)

    set(HAS_PRIMARY_ICON OFF)
    get_target_property(APPBASE_ICONS_PROPERTY ${TARGET} APPBASE_ICON)
    if (APPBASE_ICONS_PROPERTY)
        get_target_icon(${TARGET} "SCALABLE" SCALABLE_IMAGE)
        get_target_icon(${TARGET} "1024x1024" 1024x1024_IMAGE)
        get_target_icon(${TARGET} "512x512" 512x512_IMAGE)
        get_target_icon(${TARGET} "256x256" 256x256_IMAGE)
        get_target_icon(${TARGET} "128x128" 128x128_IMAGE)
        get_target_icon(${TARGET} "64x64" 64x64_IMAGE)
        get_target_icon(${TARGET} "48x48" 48x48_IMAGE)
        get_target_icon(${TARGET} "32x32" 32x32_IMAGE)
        get_target_icon(${TARGET} "16x16" 16x16_IMAGE)
        set(APPBASE_ICONS
                "scalable^_${SCALABLE_IMAGE}"
                "1024x1024^_${1024x1024_IMAGE}"
                "512x512^_${512x512_IMAGE}"
                "256x256^_${256x256_IMAGE}"
                "128x128^_${128x128_IMAGE}"
                "64x64^_${64x64_IMAGE}"
                "48x48^_${48x48_IMAGE}"
                "32x32^_${32x32_IMAGE}"
                "16x16^_${16x16_IMAGE}"
        )
        foreach (APPBASE_ICON ${APPBASE_ICONS})
            string(REPLACE "^_" ";" icon_ "${APPBASE_ICON}")
            list(GET icon_ 0 icon_res)
            list(GET icon_ 1 icon_location)
            if (icon_location)
                get_filename_component(icon_ext "${icon_location}" LAST_EXT)
                set(icon_out "${icon_res}/apps/${ICON_NAME}${icon_ext}")
                file(MAKE_DIRECTORY "${OUT_DIR}/${icon_res}/apps")
                file(COPY_FILE "${icon_location}" "${OUT_DIR}/${icon_out}")
                if (NOT HAS_PRIMARY_ICON)
                    set(${PRIMARY_ICON} "${icon_out}" PARENT_SCOPE)
                    set(HAS_PRIMARY_ICON ON)
                endif ()
            endif ()
        endforeach ()
    else ()
        message(WARNING "QtAppBase: Missing an AppImage icon which is mandatory. Using a placeholder icon.")
        file(DOWNLOAD "https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/application-brackets-outline.svg" "${CMAKE_CURRENT_BINARY_DIR}/.qtappbase/placeholder.svg")
        set_target_properties(${TARGET} PROPERTIES APPBASE_ICON "scalable^_${CMAKE_CURRENT_BINARY_DIR}/.qtappbase/placeholder.svg")
        create_appimage_icons_dir(${TARGET} ${ICON_NAME} ${OUT_DIR} icon_out)
        set(${PRIMARY_ICON} "${icon_out}" PARENT_SCOPE)
    endif ()
endfunction()
